fail_fast: false # fixers should be false, linters should be true
exclude: |
  (?x)^(
      docs/ |
      another/example/directory/to_exclude/
  )|(?x)^(
      example/file/to_exclude.py |
      another/example/file/to_exclude.py
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: "requirements.txt" # todo: https://github.com/jazzband/pip-tools/issues/1448
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-sort-keys, --no-ensure-ascii]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/jazzband/pip-tools
    rev: 6.6.0
    hooks:
      - id: pip-compile
        args: [requirements.in]
        files: requirements.in

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: [--ignore-words=.dictionary, -w]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        types_or: [css, javascript, html, yaml]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.15.0
    hooks:
      - id: eslint
        additional_dependencies:
          [
            "eslint@8.15.0",
            "eslint-config-prettier@8.5.0",
            "@babel/eslint-parser@7.17.0",
            "@babel/core@7.17.10",
            "eslint-plugin-no-unsanitized@4.0.1",
          ]
        args: [--fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
      - id: check-yaml
        fail_fast: true # applies to check-yaml as well as every hook below
      - id: name-tests-test

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-pytest-style==1.6.0,
            flake8-bugbear==22.4.25,
            flake8-comprehensions==3.9.0,
            flake8-print==4.0.1,
            flake8-pytest-style==v1.6.0,
            darglint==v1.8.1,
          ]
          # maybe add flake8-simplify?

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [--severity-level=high, --confidence-level=high]

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        additional_dependencies:
          [
            stylelint@14.8.2,
            stylelint-config-standard@25.0.0,
            stylelint-config-prettier@9.0.3,
          ]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
      - id: validate-html

  - repo: https://github.com/pre-commit/mirrors-scss-lint
    rev: v0.59.0
    hooks:
      - id: scss-lint

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.4
    hooks:
      - id: python-safety-dependencies-check

  # pylint should be last and verbose because it has the most useful report
  - repo: https://github.com/PyCQA/pylint
    rev: v2.13.8
    hooks:
      - id: pylint
        verbose: true
        args:
          [
            "--fail-under=9.0",
            "--fail-on=E,trailing-comma-tuple,pointless-statement,wildcard-import,unreachable,redefined-builtin,bare-except,dangerous-default-value,too-complex,unspecified-encoding",
          ]
        additional_dependencies: [pylint_requests==0.1.1, pyenchant==3.2.2]
