name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    env:
      MERGE_LABELS: ""
      UPDATE_LABELS: ""
      MERGE_METHOD: "squash"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:

      - name: "Event name is: ${{ github.event_name }}"
        run: echo "Event name is:" ${{ github.event_name }}

      - name: "Event type is: ${{ github.event.action }}"
        run: echo "Event type is:" ${{ github.event.action }}


      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
