name: automerge
on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    env:
      UPDATE_LABELS: ""
      UPDATE_METHOD: "merge"
      MERGE_LABELS: ""
      MERGE_METHOD: "squash"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      # append additional users here to allow automerge for them
      USER_ALLOWLIST: '["${{github.repository_owner}}", "dependabot"]'

    steps:
      - name: "Context Info"
        run: |
          echo "github.event_name:" ${{github.event_name}}
          echo "github.event.action:" ${{github.event.action}}
          echo "github.actor:" ${{github.actor}}
          echo "github.repository_owner:" ${{github.repository_owner}}
          echo "github.event.pull_request.user.login:" ${{github.event.pull_request.user.login}}

      - name: automerge
        # Only automerge if both the actor and the pull request user are in the USER_ALLOWLIST
        if: >-
          ${{
            contains(fromJSON(env.USER_ALLOWLIST), github.actor) &&
            contains(fromJSON(env.USER_ALLOWLIST), github.event.pull_request.user.login)
          }}
        id: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
