name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

env:
  approved_automergers: '["${{github.repository_owner}}", "octocat"]' # add more users to the array to allow them to auto-merge

jobs:
  automerge:
    if: contains(fromJSON(env.approved_automergers), github.actor)
    runs-on: ubuntu-latest
    env:
      UPDATE_LABELS: ""
      UPDATE_METHOD: "merge"
      MERGE_LABELS: ""
      MERGE_METHOD: "squash"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - name: "print context"
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}
          echo ${{ github.actor }}

      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
