name: automerge
on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  automerge:
    # append additional users allowed to automerge below
    #if: >-
    #  ${{
    #    github.actor == github.repository_owner ||
    #    github.actor == 'dependabot'
    #  }}
    runs-on: ubuntu-latest
    env:
      UPDATE_LABELS: ""
      UPDATE_METHOD: "merge"
      MERGE_LABELS: ""
      MERGE_METHOD: "squash"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - name: Sender
        run: echo ${{github.event.pull_request.user.login}}
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

      - name: "print context info"
        run: |
          echo "github.event_name:" ${{github.event_name}}
          echo "github.event.action:" ${{github.event.action}}
          echo "github.actor:" ${{github.actor}}
          echo "github.repository_owner:" ${{github.repository_owner}}

      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
