name: autoupdate

on:
  pull_request:

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      uses: chinthakagodawita/autoupdate@v1
      env:
        GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
