name: automerge
on:
  pull_request_target:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest
    env:
      # append additional users to the USER_ALLOWLIST to allow automerge for them
      USER_ALLOWLIST: |
        '[
          "${{github.repository_owner}}",
          "dependabot"
        ]'
    steps:
      - name: "Print Context Info"
        run: |
          echo "github.event_name:" ${{github.event_name}}
          echo "github.event.action:" ${{github.event.action}}
          echo "github.actor:" ${{github.actor}}
          echo "github.repository_owner:" ${{github.repository_owner}}
          echo "github.event.pull_request.user.login:" ${{github.event.pull_request.user.login}}
          echo "github.event.pull_request.number:" ${{github.event.pull_request.number}}
          echo "allow list:" ${{ env.USER_ALLOWLIST }}
          echo "actor approved": ${{contains(fromJSON(env.USER_ALLOWLIST), github.actor)}}
          echo "pull_request.user.login approved": ${{contains(fromJSON(env.USER_ALLOWLIST), github.event.pull_request.user.login)}}
          echo "bad_guy approved": ${{contains(fromJSON(env.USER_ALLOWLIST), 'bad_guy')}}
          

      - name: automerge
        if: |
          ${{
            contains(fromJSON(env.USER_ALLOWLIST), github.actor) &&
            contains(fromJSON(env.USER_ALLOWLIST), github.event.pull_request.user.login)
          }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          pull-request-number: ${{github.event.pull_request.number}}
          merge-method: squash
