name: autoupdate workflow

on:
  pull_request:

concurrency:
  group: ci-tests-${{github.ref}}-testing
  cancel-in-progress: true

jobs:
  autoupdate_job:
    name: autoupdate job
    runs-on: ubuntu-latest
    steps:
      - name: attempt autoupdate with PAT
        id: autoupdate_pat
        continue-on-error: true
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{secrets.PAT}}"

      - name: fallback to autoupdate with GITHUB_TOKEN
        if: steps.autoupdate_pat.outcome != 'success'
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
