name: autoupdate workflow

on:
  pull_request:

jobs:
  autoupdate_job:
    name: autoupdate job
    runs-on: ubuntu-latest
    steps:
      uses: chinthakagodawita/autoupdate@v1
      env:
        GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
