name: Pull Check Twice

on:
  pull_request_target:
    branches: ["main"]

jobs:
  pull_check_again:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.head_ref }}
          check-name: "Code Testing"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: my-event
