name: run tests

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Test with bandit
      run: |
        bandit -x .\tests -r .

    - name: Commit report
      run: |
        git config --global user.name 'CI Tests'
        git config --global user.email 'grintor@users.noreply.github.com'
        git commit -am "Automated CI report update"
        git push
      continue-on-error: true