name: Code Testing

on:
  push:
    branches-ignore: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cleanup_and_tests:
    runs-on: ubuntu-latest

    steps:
      - run: echo "event name is:" ${{ github.event_name }}
      - run: echo "event type is:" ${{ github.event.action }}

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: test with pytest
        run: |
          pytest

      - name: pre-commit auto-fix
        run: |
          pre-commit run --all-files
        continue-on-error: true

      - name: test with pre-commit
        run: |
          pre-commit run --all-files

      - name: commit report
        run: |
          git config --global user.name 'CI Tests'
          git config --global user.email 'grintor@users.noreply.github.com'
          git commit -am "Automated CI update"
          git push
        continue-on-error: true
