name: Code Testing

on:
  push:
    branches-ignore: ["main"]

jobs:
  cleanup_and_tests:
    runs-on: ubuntu-latest

    steps:
      - name: "print context info"
        run: |
          echo "github.event_name:" ${{github.event_name}}
          echo "github.event.action:" ${{github.event.action}}
          echo "github.actor:" ${{github.actor}}

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          pip-compile requirements.in -q
          pip install -r requirements.txt

      - name: test with pytest
        run: |
          pytest

      - name: pre-commit auto-fix
        run: |
          pre-commit run --all-files
        continue-on-error: true

      - name: test with pre-commit
        run: |
          pre-commit run --all-files

      - name: build docs
        run: |
          rm -rf docs
          sphinx-build -W --keep-going -a -b dirhtml docs-src docs
          touch docs/.nojekyll


      - name: commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git rm -r --cached .
          git add .
          git commit -am "🤖 Automated CI update [skip actions]"
          git push
        continue-on-error: true
